import { timingSafeEqual } from 'node:crypto';
import { db, json } from '../lib/db.js';
import { CURVE_GAMMA, CURVE_MAX_ODDS, CURVE_MIN_ODDS, HOUSE_FEE_RATE, marketQuote } from '../lib/odds.js';

const DAILY_GRANT = 10000;
function authorized(req){const e=String(process.env.ADMIN_KEY||'').trim(),s=String(req.headers['x-admin-key']||'').trim();if(!e)return{ok:false,status:503,error:'ADMIN_KEY is not configured in Vercel.'};if(!s)return{ok:false,status:401,error:'Admin key is required.'};const a=Buffer.from(e),b=Buffer.from(s);return a.length===b.length&&timingSafeEqual(a,b)?{ok:true}:{ok:false,status:403,error:'Invalid admin key.'}}

export default async function handler(req,res){
 if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});const auth=authorized(req);if(!auth.ok)return json(res,auth.status,{error:auth.error});
 try{const sql=db();
  const [config]=await sql`SELECT title,close_at,now() AS server_now FROM market_config WHERE id=1`;
  const candidates=await sql`SELECT c.id,c.name,c.role,c.initials,c.sort_order,c.seed_pool,c.admin_weight,COALESCE(SUM(b.stake),0)::int AS gross_pool,COALESCE(SUM(b.effective_stake),0)::int AS effective_pool,COALESCE(SUM(b.fee_amount),0)::int AS fee_pool,COUNT(b.id)::int AS bet_count FROM candidates c LEFT JOIN bets b ON b.candidate_id=c.id GROUP BY c.id,c.name,c.role,c.initials,c.sort_order,c.seed_pool,c.admin_weight ORDER BY c.sort_order`;
  const [stats]=await sql`SELECT COALESCE(SUM(stake),0)::int AS gross_volume,COALESCE(SUM(effective_stake),0)::int AS effective_pool,COALESCE(SUM(fee_amount),0)::int AS house_fee,COUNT(*)::int AS trades,COUNT(DISTINCT player_id)::int AS players,COUNT(*) FILTER(WHERE created_at>=now()-interval '60 minutes')::int AS trades_60m FROM bets`;
  const activity=await sql`SELECT b.id,b.stake,b.effective_stake,b.fee_amount,b.odds_at_bet,b.created_at,p.nickname,c.name AS candidate_name,c.initials FROM bets b JOIN players p ON p.id=b.player_id JOIN candidates c ON c.id=b.candidate_id ORDER BY b.created_at DESC LIMIT 100`;
  const bettors=await sql`SELECT p.nickname,COUNT(b.id)::int AS bet_count,COALESCE(SUM(b.stake),0)::int AS total_stake,(GREATEST(p.starting_balance,${DAILY_GRANT}*(1+GREATEST(0,FLOOR(EXTRACT(EPOCH FROM(now()-p.created_at))/86400)::int)))-p.spent)::int AS balance,MAX(b.created_at) AS last_bet_at FROM players p LEFT JOIN bets b ON b.player_id=p.id GROUP BY p.id,p.nickname,p.starting_balance,p.spent,p.created_at HAVING COUNT(b.id)>0 ORDER BY total_stake DESC LIMIT 100`;
  const playerRows=await sql`SELECT b.candidate_id,p.nickname,COALESCE(SUM(b.stake),0)::int AS gross_stake,COALESCE(SUM(b.effective_stake),0)::int AS effective_stake FROM bets b JOIN players p ON p.id=b.player_id GROUP BY b.candidate_id,p.id,p.nickname`;
  const totalEffective=Number(stats?.effective_pool||0),grossVolume=Number(stats?.gross_volume||0),houseFee=Number(stats?.house_fee||0);
  const markets=candidates.map(c=>{const effective=Number(c.effective_pool||0),gross=Number(c.gross_pool||0),adminWeight=Number(c.admin_weight||0),seed=Number(c.seed_pool||0),pricingWeight=seed+adminWeight,q=marketQuote(effective,totalEffective,pricingWeight);return{id:c.id,name:c.name,role:c.role,initials:c.initials,bet_count:Number(c.bet_count||0),gross_pool:gross,effective_pool:effective,user_volume:effective,fee_pool:Number(c.fee_pool||0),seed_weight:seed,admin_weight:adminWeight,pricing_weight:pricingWeight,share:q.userShare,pricingShare:q.pricingShare,naturalOdds:q.naturalOdds,curveOdds:q.curveOdds,decimalOdds:q.decimalOdds}});
  const settlement=markets.map(c=>{const rows=playerRows.filter(r=>r.candidate_id===c.id).map(r=>{const payout=Number(r.effective_stake||0)*c.decimalOdds;return{nickname:r.nickname,grossStake:Number(r.gross_stake||0),effectiveStake:Number(r.effective_stake||0),payout,profit:payout-Number(r.gross_stake||0)}});const payoutLiability=rows.reduce((s,r)=>s+r.payout,0),biggestWinner=[...rows].sort((a,b)=>b.payout-a.payout)[0]||null;return{candidateId:c.id,candidateName:c.name,share:c.share,pricingShare:c.pricingShare,currentOdds:c.decimalOdds,payoutLiability,housePL:grossVolume-payoutLiability,biggestWinner}});
  const currentLeader=[...markets].sort((a,b)=>b.share-a.share)[0]||null,leaderSettlement=currentLeader?settlement.find(s=>s.candidateId===currentLeader.id):null,worstCase=[...settlement].sort((a,b)=>a.housePL-b.housePL)[0]||null,bestCase=[...settlement].sort((a,b)=>b.housePL-a.housePL)[0]||null;
  return json(res,200,{title:config?.title,closeAt:config?.close_at,serverNow:config?.server_now,open:config?new Date(config.server_now)<new Date(config.close_at):false,grossVolume,effectivePool:totalEffective,totalPool:totalEffective,houseFee,guaranteedHouseFloor:houseFee,feeRate:HOUSE_FEE_RATE,trades:Number(stats?.trades||0),trades60m:Number(stats?.trades_60m||0),players:Number(stats?.players||0),dailyGrant:DAILY_GRANT,rateModel:{type:'house-safe-curve',minOdds:CURVE_MIN_ODDS,maxOdds:CURVE_MAX_ODDS,gamma:CURVE_GAMMA,settlement:'final-pool'},markets,settlement,leaderSettlement,worstCase,bestCase,activity:activity.map(a=>({...a,stake:Number(a.stake),effective_stake:Number(a.effective_stake),fee_amount:Number(a.fee_amount),odds_at_bet:a.odds_at_bet==null?null:Number(a.odds_at_bet)})),bettors});
 }catch(error){console.error('admin market api error',error);return json(res,500,{error:'Unable to load admin market.'})}
}
